# Generated by Django 5.2.17 on 2026-08-08 08:15

import uuid
from decimal import Decimal

from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        default=apps.core.models.new_session_token,
                        editable=False,
                        help_text="Bearer credential carried in the signed cis_session cookie.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, default=apps.core.models.default_expiry),
                ),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=10),
                ),
                ("demo_seeded", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["expires_at"], name="core_sessio_expires_4be96c_idx")
                ],
            },
        ),
    ]
