# Generated by Django 5.2.17 on 2026-08-08 11:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("classify", "Classification"),
                            ("requirement_extract", "Requirement extraction"),
                            ("requirement_match", "Requirement matching"),
                            ("interview_prep", "Interview prep"),
                            ("judge", "Eval judge"),
                        ],
                        max_length=24,
                    ),
                ),
                ("model", models.CharField(max_length=64)),
                ("effort", models.CharField(blank=True, max_length=16)),
                ("backend", models.CharField(default="anthropic", max_length=16)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveIntegerField(default=0)),
                ("cache_creation_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=10),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("ttft_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("stop_reason", models.CharField(blank=True, max_length=32)),
                ("error_type", models.CharField(blank=True, max_length=64)),
                ("anthropic_request_id", models.CharField(blank=True, max_length=128)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_calls",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["-created_at"], name="observabili_created_dd101c_idx"),
                    models.Index(
                        fields=["session", "-created_at"], name="observabili_session_726d8e_idx"
                    ),
                ],
            },
        ),
    ]
