# Generated by Django 5.2.17 on 2026-08-08 08:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("resume", "Résumé"), ("job", "Job description")], max_length=16
                    ),
                ),
                ("ordinal", models.PositiveSmallIntegerField(default=0)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("file", models.FileField(blank=True, null=True, upload_to="documents/")),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("page_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("parsing", "Parsing"),
                            ("chunking", "Chunking"),
                            ("embedding", "Embedding"),
                            ("analyzing", "Analyzing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=32)),
                ("error_detail", models.TextField(blank=True)),
                ("normalized_text", models.TextField(blank=True)),
                ("text_sha256", models.CharField(blank=True, max_length=64)),
                ("embedding_model", models.CharField(blank=True, max_length=100)),
                ("injection_flag", models.BooleanField(default=False)),
                ("injection_reasons", models.JSONField(blank=True, default=list)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "ordering": ("kind", "ordinal"),
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("heading", models.CharField(blank=True, max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("experience", "Experience"),
                            ("education", "Education"),
                            ("skills", "Skills"),
                            ("projects", "Projects"),
                            ("certifications", "Certifications"),
                            ("about", "About"),
                            ("responsibilities", "Responsibilities"),
                            ("requirements", "Requirements"),
                            ("nice_to_have", "Nice_To_Have"),
                            ("benefits", "Benefits"),
                            ("legal", "Legal"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("char_start", models.PositiveIntegerField()),
                ("char_end", models.PositiveIntegerField()),
                ("is_boilerplate", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="documents.document",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "ordering": ("document", "order"),
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["session", "kind"], name="documents_d_session_dc8cfa_idx"),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("session", "kind", "ordinal"), name="unique_ordinal_per_kind_per_session"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("page_count__lte", 30)), name="page_count_within_cap"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["document", "order"], name="documents_s_documen_ab7012_idx"),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.CheckConstraint(
                condition=models.Q(("char_end__gte", models.F("char_start"))),
                name="section_span_is_not_inverted",
            ),
        ),
    ]
