# Generated by Django 5.2.17 on 2026-08-08 08:57

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_session"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ordinal", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("char_start", models.PositiveIntegerField()),
                ("char_end", models.PositiveIntegerField()),
                ("embed_text", models.TextField()),
                ("token_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
                ),
                ("is_boilerplate", models.BooleanField(default=False)),
                ("injection_flag", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chunks",
                        to="documents.section",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "ordering": ("document", "ordinal"),
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="chunk_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="chunk_search_vector_gin"
                    ),
                    models.Index(fields=["session", "document"], name="chunk_session_document"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "ordinal"), name="unique_chunk_ordinal_per_document"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("char_end__gt", models.F("char_start"))),
                        name="chunk_span_is_not_empty",
                    ),
                ],
            },
        ),
    ]
