# Generated by Django 5.2.17 on 2026-08-08 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_chunk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
    ]
