# Generated by Django 5.2.17 on 2026-08-08 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_session"),
        ("documents", "0002_chunk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("skill", models.CharField(db_index=True, max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hard_skill", "Hard skill"),
                            ("tool", "Tool"),
                            ("domain", "Domain"),
                            ("soft_skill", "Soft skill"),
                            ("credential", "Credential"),
                            ("seniority", "Seniority"),
                        ],
                        default="hard_skill",
                        max_length=16,
                    ),
                ),
                ("must_have", models.BooleanField(default=True)),
                ("evidence_char_start", models.PositiveIntegerField(default=0)),
                ("evidence_char_end", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("deterministic", "Deterministic (no API key)"),
                            ("llm", "Claude"),
                        ],
                        default="deterministic",
                        max_length=16,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="documents.document",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "ordering": ("document", "order"),
            },
        ),
        migrations.CreateModel(
            name="RequirementMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("strong", "Strong"),
                            ("partial", "Partial"),
                            ("missing", "Missing"),
                        ],
                        max_length=8,
                    ),
                ),
                ("rationale", models.CharField(blank=True, max_length=280)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("deterministic", "Deterministic (no API key)"),
                            ("llm", "Claude"),
                        ],
                        default="deterministic",
                        max_length=16,
                    ),
                ),
                (
                    "evidence_chunks",
                    models.ManyToManyField(
                        blank=True, related_name="matches", to="documents.chunk"
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="analysis.requirement",
                    ),
                ),
                (
                    "resume_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_matches",
                        to="documents.document",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.session",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="requirement",
            index=models.Index(fields=["document", "order"], name="analysis_re_documen_6b8b03_idx"),
        ),
        migrations.AddConstraint(
            model_name="requirementmatch",
            constraint=models.UniqueConstraint(
                fields=("requirement", "resume_document"), name="unique_match_per_requirement"
            ),
        ),
    ]
