# Generated by Django 5.2.17 on 2026-08-08 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_session"),
        ("documents", "0002_chunk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")], max_length=16
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("analysis", "Analysis"), ("interview", "Interview prep")],
                        default="analysis",
                        max_length=16,
                    ),
                ),
                ("intent", models.CharField(blank=True, max_length=24)),
                ("scope_job_ids", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("streaming", "Streaming"),
                            ("complete", "Complete"),
                            ("refused", "Refused"),
                            ("no_context", "No context"),
                            ("error", "Error"),
                        ],
                        default="complete",
                        max_length=16,
                    ),
                ),
                (
                    "refusal_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("out_of_scope", "Out of scope"),
                            ("fabrication_request", "Fabrication request"),
                            ("model_refusal", "Model refusal"),
                            ("rate_limited", "Rate limited"),
                            ("budget_exhausted", "Budget exhausted"),
                        ],
                        max_length=32,
                    ),
                ),
                ("stop_reason", models.CharField(blank=True, max_length=32)),
                ("grounding_max_score", models.FloatField(default=0.0)),
                ("prompt_version", models.CharField(blank=True, max_length=32)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("index", models.PositiveSmallIntegerField()),
                ("doc_char_start", models.PositiveIntegerField()),
                ("doc_char_end", models.PositiveIntegerField()),
                ("cited_text", models.TextField()),
                ("answer_char", models.PositiveIntegerField(default=0)),
                (
                    "chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.chunk",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "ordering": ("message", "index"),
            },
        ),
        migrations.CreateModel(
            name="RetrievalTrace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.TextField()),
                ("expanded_query", models.TextField(blank=True)),
                ("scope_job_ids", models.JSONField(blank=True, default=list)),
                ("resolved_from", models.CharField(blank=True, max_length=64)),
                ("dense_hits", models.JSONField(blank=True, default=list)),
                ("lexical_hits", models.JSONField(blank=True, default=list)),
                ("fused", models.JSONField(blank=True, default=list)),
                ("selected_chunk_ids", models.JSONField(blank=True, default=list)),
                ("anchors_applied", models.JSONField(blank=True, default=list)),
                ("quota_applied", models.BooleanField(default=False)),
                ("max_score", models.FloatField(default=0.0)),
                ("context_chars", models.PositiveIntegerField(default=0)),
                ("timings_ms", models.JSONField(blank=True, default=dict)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trace",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session", "created_at"], name="chat_messag_session_4940cf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="citation",
            constraint=models.UniqueConstraint(
                fields=("message", "index"), name="unique_citation_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="citation",
            constraint=models.CheckConstraint(
                condition=models.Q(("doc_char_end__gt", models.F("doc_char_start"))),
                name="citation_span_non_empty",
            ),
        ),
    ]
